data("cars")
linearModel <- lm(dist~speed, data=cars)
newCar <- data.frame(speed=25)
result <- predict(linearModel, newCar)
print(result)
plot(cars$speed, cars$dist)
abline(linearModel)

#x <- c(10,20,30,40,60)
#y <- c(10,20,30,40,50)
#relation <- lm(y~x)
#a <- data.frame(x=70)
#plot(y,x)
#abline(relation)
#result <- predict(relation, a)
#print(result)